### ISSUE TITLE
Copy-trade from Arbitrum: extending SMS-Telegram Wallet

### ISSUE THREAD

**Issue by polymorpher** [polymorpher/sms-wallet#24]
(Moved from https://github.com/hiddenstate/docs/issues/6)

Notes moved to https://hackmd.io/@polymorpher/telegram-wallet-copy-trades

See https://www.x.country/harmony-2024-defi-a3e0e851036c45c8ace41bd2aadd6f56

**Comment by jwst9** [comment]
- Trading wallet identification system
For wallets created from this project or all the wallets on the chain? and which chain? Arbitrum?

- Fast-trading wallet in SMS-Telegram Wallet

> create a unique hot wallet for each user where the server maintains the private key

What does "each user" mean?
Does the server keep private key against being non-custodiality?
I remember the tgbot triggers webview popup from the telegram and the webview shows page hosted from `client` app

**Comment by polymorpher** [comment]
For all wallets, on Arbitrum.

Each user means each (SMS) Telegram wallet user that enabled copy-trading. This is a separate wallet from the user's Telegram wallet

**Comment by polymorpher** [comment]
Let's put development of this on hold for now. Other projects are taking priority

**Comment by polymorpher** [comment]
Notes moved to https://hackmd.io/@polymorpher/telegram-wallet-copy-trades
